// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Account struct {
	ID       *int       `json:"id,omitempty" gorm:"primaryKey"`
	FullName *string    `json:"fullName,omitempty" gorm:"fullName"`
	Email    *string    `json:"email,omitempty" gorm:"email"`
	Address  *string    `json:"address,omitempty" gorm:"address"`
	Phone    *string    `json:"phone,omitempty" gorm:"phone"`
	Avatar   *string    `json:"avatar,omitempty" gorm:"avatar"`
	Sex      *string    `json:"sex,omitempty" gorm:"sex"`
	Birthday *time.Time `json:"birthday,omitempty" gorm:"sex"`
	Token    *string    `json:"token,omitempty"`
	Code     *string    `json:"code,omitempty"`
	Msg      *string    `json:"msg,omitempty"`
}

type Category struct {
	ID          *int       `json:"id,omitempty" gorm:"primaryKey"`
	Title       *string    `json:"title,omitempty" gorm:"title"`
	Description *string    `json:"description,omitempty" gorm:"description"`
	Thumbnail   *string    `json:"thumbnail,omitempty" gorm:"thumbnail"`
	Status      *string    `json:"status,omitempty" gorm:"status"`
	Position    *int       `json:"position,omitempty" gorm:"position"`
	Deleted     *bool      `json:"deleted,omitempty" gorm:"deleted"`
	Slug        *string    `json:"slug,omitempty" gorm:"slug"`
	Product     []*Product `json:"product"`
}

type CreateOtpInput struct {
	Email string `json:"email"`
}

type LoginAccountInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Otp struct {
	Code *string `json:"code,omitempty"`
	Msg  *string `json:"msg,omitempty"`
}

type Product struct {
	ID              *int     `json:"id,omitempty" gorm:"primaryKey"`
	Title           *string  `json:"title,omitempty" gorm:"column:title"`
	Description     *string  `json:"description,omitempty" gorm:"column:description"`
	Thumbnail       *string  `json:"thumbnail,omitempty" gorm:"column:thumbnail"`
	Price           *float64 `json:"price,omitempty" gorm:"column:price"`
	DiscountPercent *int     `json:"discountPercent,omitempty" gorm:"column:discountPercent"`
	Stock           *int     `json:"stock,omitempty" gorm:"column:stock"`
	Status          *string  `json:"status,omitempty" gorm:"column:status"`
	Position        *int     `json:"position,omitempty" gorm:"column:position"`
	Slug            *string  `json:"slug,omitempty" gorm:"column:slug"`
	Featured        *string  `json:"featured,omitempty" gorm:"column:featured"`
}

type ProductInput struct {
	Offset   *int    `json:"offset,omitempty"`
	Limit    *int    `json:"limit,omitempty"`
	Featured *string `json:"featured,omitempty"`
}

type Query struct {
}

type RegisterAccountInput struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Otp      string `json:"otp"`
}

type UpdateAccountInput struct {
	FullName *string    `json:"fullName,omitempty" gorm:"column:fullName"`
	Address  *string    `json:"address,omitempty" gorm:"column:address"`
	Phone    *string    `json:"phone,omitempty" gorm:"column:phone"`
	Avatar   *string    `json:"avatar,omitempty" gorm:"column:avatar"`
	Sex      *string    `json:"sex,omitempty" gorm:"column:sex"`
	Birthday *time.Time `json:"birthday,omitempty" gorm:"column:birthday"`
}
