// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID       *int32  `json:"id,omitempty"`
	FullName *string `json:"fullName,omitempty"`
	Email    *string `json:"email,omitempty"`
	Address  *string `json:"address,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
	Sex      *string `json:"sex,omitempty"`
	Birthday *string `json:"birthday,omitempty"`
	Token    *string `json:"token,omitempty"`
	Code     *string `json:"code,omitempty"`
	Msg      *string `json:"msg,omitempty"`
}

type Category struct {
	ID          *int32     `json:"id,omitempty"`
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	Thumbnail   *string    `json:"thumbnail,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Position    *string    `json:"position,omitempty"`
	Deleted     *bool      `json:"deleted,omitempty"`
	Slug        *string    `json:"slug,omitempty"`
	Product     []*Product `json:"product,omitempty"`
}

type CreateOtpInput struct {
	Email string `json:"email"`
}

type LoginAccountInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Otp struct {
	Code *string `json:"code,omitempty"`
	Msg  *string `json:"msg,omitempty"`
}

type Product struct {
	ID              *int32  `json:"id,omitempty"`
	Title           *string `json:"title,omitempty"`
	Description     *string `json:"description,omitempty"`
	Thumbnail       *string `json:"thumbnail,omitempty"`
	Price           *string `json:"price,omitempty"`
	DiscountPercent *string `json:"discountPercent,omitempty"`
	Stock           *string `json:"stock,omitempty"`
	Status          *string `json:"status,omitempty"`
	Position        *string `json:"position,omitempty"`
	Slug            *string `json:"slug,omitempty"`
	Featured        *string `json:"featured,omitempty"`
}

type ProductInput struct {
	Offset   *int32  `json:"offset,omitempty"`
	Limit    *int32  `json:"limit,omitempty"`
	Featured *string `json:"featured,omitempty"`
}

type Query struct {
}

type RegisterAccountInput struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Otp      string `json:"otp"`
}

type UpdateAccountInput struct {
	FullName *string `json:"fullName,omitempty"`
	Adress   *string `json:"adress,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
	Sex      *string `json:"sex,omitempty"`
	Birthday *string `json:"birthday,omitempty"`
}
